### ISSUE TITLE
confiscated weapons issue

### ISSUE THREAD

**Issue by x3003** [Realm667/boa-addons#14]
When running boa w/ 'confiscated weapons' on a recent build, I get the error: "Script error, "confiscated_weapons.pk3:mapinfo.txt" line 1496: Unknown actor class ZyklonBSteamSpawner_C3M6A"

This is w/ 1 addon enabled.

**Comment by x3003** [comment]
When removing '16652=ZyklonBSteamSpawner_C3M6A' the addon works again.

**Comment by Username-N00b-is-not-available** [comment]
Indeed... ZikShadow's comment in MAPINFO:
> // All this just so I could add to the list of equipment wipe in Astrostein, Part 2. I wish there's a cleaner way.

I wonder how he got an idea to copy the whole file instead of that particular map definition.
The issue will be fixed in an upcoming commit.
