### ISSUE TITLE
too many points given

### ISSUE THREAD

**Issue by x3003** [Realm667/boa-addons#20]
When using the score addon, shooting masked scientists gives 2500 points, which is boss level points.
Maybe a 0 too much here ?!

![Screenshot_BoA_20231007_095251](https://github.com/Realm667/boa-addons/assets/77861029/19940a06-1771-491d-b757-d58ff95de2b5)

![Screenshot_BoA_20231007_114928](https://github.com/Realm667/boa-addons/assets/77861029/4737e370-b972-4a51-8aa8-7d6511e82fcc)

**Comment by Username-N00b-is-not-available** [comment]
I think the reason was that these are rare and plot-important.

**Comment by x3003** [comment]
Well, shooting a boss gets you 2500. And they are harder to kill. So **that** should be rewarded.

**Comment by Username-N00b-is-not-available** [comment]
IIRC they are only abundant near the endgame, and it's not entirely about hardness. I wouldn't make it less than 1000.

**Comment by x3003** [comment]
That would be nice.

**Comment by AFADoomer** [comment]
They were added after the add-on was created.  The add-on falls back to giving (spawn health * 5) points if an enemy doesn't have a score amount defined.

Just add an entry to the Data/ScoreAmounts.txt file for them with an appropriate score amount.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer The score was there, and spawn health for `PlagueDoc`'s is definitely less than 500...
@Talon1024 just reduced it to 150, as with other scientists: https://github.com/Realm667/boa-addons/commit/b6b1ab44190e9c683e8a540140817804b215fbfb.

**Comment by AFADoomer** [comment]
> @AFADoomer The score was there, and spawn health for `PlagueDoc`'s is definitely less than 500... @Talon1024 just reduced it to 150, as with other scientists: [b6b1ab4](https://github.com/Realm667/boa-addons/commit/b6b1ab44190e9c683e8a540140817804b215fbfb).

That works.  I made up random numbers for the scores originally, anyway...  Probably was thinking that was the Schabbs mini-boss.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Do you have any ideas on https://github.com/Realm667/WolfenDoom/issues/1318#issuecomment-1595376092 except #1296..?
