### ISSUE TITLE
Vampire addon crashes gzdoom 4.11 and latest git version BoA

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/boa-addons#22]
As the subject says. Part of the error message is ...

Attempt to override non-existent virtual function SetVisibility

Interestingly I get the same with Score addon.

**Comment by x3003** [comment]
Are you sure you have the latest boa addons ?
I thought SetVisibility was replaced by IsVisible some time ago.

**Comment by hawkwind3** [comment]
That was it, thanks. Still looking at other addon issues though ..

This one in particular closed.

**Comment by hawkwind3** [comment]
Closed.
