### ISSUE TITLE
missing creditsFull_de for m2hb and more_weapons

### ISSUE THREAD

**Issue by mgrinzPlayer** [Realm667/boa-addons#3]
I'm working on Polish translation. I will send PR after this issue closing.

**Comment by Tormentor667** [comment]
Added

**Comment by mgrinzPlayer** [comment]
@Tormentor667, more_weapons

@all, there's no need to use title_{lang} if you use the same exact string for each lang, e.g. "Instagib"
https://github.com/mgrinzPlayer/BoaLauncher/blob/0e19457e64e276322651d13a169e2704321f4f60/parsing.inc#L78-L89
