### ISSUE TITLE
vampire issue

### ISSUE THREAD

**Issue by x3003** [Realm667/boa-addons#5]
When starting a game (boa 3.1) with vampire, I get this error message: vampire.pk3:scripts/statusbar.zs, line 39: Attempt to override non-existent virtual function IsVisible

**Comment by AFADoomer** [comment]
Already fixed in the add-ons repository.

**Comment by x3003** [comment]
I downloaded it just now and compiled it, and it still gives the error.

**Comment by x3003** [comment]
Rechecked, seems to work now.
